import type { Metadata } from "next"
import { Inter, Playfair_Display } from "next/font/google"
import "./globals.css"

import Header from "./components/header"
import Footer from "./components/footer"

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const playfairDisplayFont = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${playfairDisplayFont.variable} antialiased bg-background`}
      >
        <Header />
        <main className="mx-auto px-6 max-w-360">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
